spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@dearlavioncluster.xnanadi.mongodb.net/notification-service?retryWrites=true&w=majority&appName=DearLavionCluster
      auto-index-creation: true
      socket-timeout: 20000
      connect-timeout: 10000
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: dearlavion-notification-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.dearlavion.notification.kafka.dto.WishEvent
  mail:
    host: smtp.gmail.com
    port: 587
    username: dearlavion@gmail.com
    password: zplbgfewlboykxlp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8083
  address: 0.0.0.0

auth:
  server:
    url: http://localhost:8081

logging:
  level:
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG