spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@dearlavioncluster.xnanadi.mongodb.net/notification-service?retryWrites=true&w=majority&appName=DearLavionCluster
      auto-index-creation: true
      socket-timeout: 20000
      connect-timeout: 10000
  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: dearlavion-notification-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: org.example.kafka.dto.WishEvent

server:
  port: 8083
  address: 0.0.0.0